resources:
  repositories:
    - repository: templatesRepo
      type: git
      ref: main
      name: pipeline-templates
    - repository: commonsRepo
      type: git
      ref: main
      name: commons

variables:
    - name: project
      value: System_Integrations

    - name: pathToFiles
      value: ${{variables.Project}}\ScmImport\System_Integration

    - name: env
      value: Prod # Dev, Homolog, Prod...

    - name: vmName
      value: PWRJO1-RDK-01

    - name: branchName
      value: main


trigger:
  - main

pool:
  name: Default

stages:
- template: Python/default_ci.yml@templatesRepo
  parameters:
    stageName: Build
    project: ${{ variables.project }}
    pythonVersion: '3.11'
    installDependencies: true
    runTests: true

- template: Python/default_cd.yml@templatesRepo
  parameters:
    stageName: Deploy
    dependsOn: Build
    project: ${{ variables.project }}
    env: ${{ variables.env }}
    vmName: ${{ variables.vmName }}
    targetFolder: 'ScmImport'
    installDependencies: true

- template: Rundeck/default_rdk.yml@templatesRepo
  parameters:
    stageName: RundeckUpdate
    dependsOn: Deploy
    project: ${{ variables.project }}
    env: ${{ variables.env }}
    vmName: ${{ variables.vmName }}
    runJobDiscovery: true
    jobSourceFolders: 
      - '${{ variables.pathToFiles }}\ServiceNow'
    runAclUpdate: true
    aclSourceFolders:
      - '${{ variables.project }}' 
    aclTargetFolder: 'etc'

# - template: Git/update_branches.yml@templatesRepo
#   parameters:
#     stageName: GitUpdate
#     dependsOn: RundeckUpdate
#     project: ${{ variables.project }}
#     env: ${{ variables.env }}
#     vmName: ${{ variables.vmName }}
#     mergeBranch: ${{ variables.branchName }}
#     branchesToUpdate:
#       - dev
#       - homolog